#!/usr/bin/env bash
# Script installs Nginx on a server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

#Setting permissions for web root directory
sudo chown -R www-data:www-data /var/www/html
sudo chmod -R 755 /var/www/html

# Create a basic HTML file with the required content
echo "Hello World!" | sudo tee /var/www/html/index.html
# testing nginx config
sudo nginx -t

sudo service nginx restart
