#!/usr/bin/env bash
# Script installs Nginx on a server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# testing nginx config
sudo nginx -t

sudo service nginx restart
