#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

REDIRECT_BLOCK="location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}
sudo sed -i "s/server_name _;/$REDIRECT_BLOCK/" /etc/nginx/sites-available/default

sudo service nginx restart
