#!/usr/bin/env bash
#Install nginx

apt-get update -y
apt-get upgrade -y

apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

service nginx start

sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx reload
