#!/usr/bin/env bash
# Install nginx

apt-get update -y
apt-get upgrade -y
apt-get install -y nginx

# Set up a 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx reload
