#!/bin/bash

# Ignore SC2154
# shellcheck disable=SC2154

# Install Nginx
sudo apt update
sudo apt install -y nginx

# Update Nginx configuration
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOL
server {
    listen 80;

    server_name _;

    location / {
        add_header X-Served-By \$hostname;
    }
}
EOL

# Restart Nginx to apply changes
sudo sservice restart nginx
