#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend kamandaerick.tech
    timeout client  30000
    bind 0:80
    default_backend kamandaerick.tech_backend

backend kamandaerick.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 310284-web-01 100.26.165.82 check
    server 310284-web-02 52.3.242.197 check
EOT

sudo service haproxy restart
