#!/usr/bin/env bash

#This script displays PID with process whose name contain the word bash
for pid_dir in /proc/*/; do
    pid=$(basename "$pid_dir")

    if [[ -e "/proc/$pid/cmdline" ]]; then
        process_name=$(cat "/proc/$pid/cmdline" | tr -d '\0')

           if [[ "$process_name" == *"bash"* ]]; then
            echo "$pid $process_name"
        fi
    fi
done
