#!/usr/bin/env bash

# Find the PID of the "7-highlander" process
process_name="7-highlander"
pid=$(pgrep -f "$process_name")

if [ -n "$pid" ]; then

    echo "Terminating process $process_name (PID: $pid)..."
    kill -s SIGTERM "$pid"
    sleep 2
    echo "Terminated."
fi

