#!/bin/bash

#Kill the process 7-highlander
process_name="7-highlander"
pid=$(pgrep -f "$process_name")

if [ -n "$pid" ]; then
    kill -s SIGTERM "$pid"
    echo "Killed"
else
    echo "Process $process_name not found."
fi
