#!/usr/bin/env bash
#This script displays contents of the current directory
#in a list format where only part of the name after the
#first dash is display

for file in *; do
	if [[ -f "$file" ]]; then
		name=$(echo "$file" | cut -d '_' -f 2-)
	echo "$name"
	fi
done
