#!/usr/bin/env bash
#This script displays contents of the current directory
#in a list format where only part of the name after the
#first dash is display

files=$(ls)
for file in $files; do
	if [[ $file == "." ]]; then
		continue
	fi
	file_name=("${file//-/ }")
	echo "${file_name[1]}"
done
