#!/usr/bin/env bash
#This script gives information about the school file

file_path="school"

if [ -e "$file_path" ]; then
    echo "school file exists"
    
    if [ -s "$file_path" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    
    if [ -f "$file_path" ]; then
        echo "school is a regular file"
    elif [ -d "$file_path" ]; then
        echo "school is a directory"
    fi
else
    echo "school file does not exist"
fi
