#!/usr/bin/env bash
#Installs ufw on a server and blocks all traffic except those through ports 22, 443, and 80

#Installation command
sudo apt-get install -y ufw

#Deny all incoming and outgoing traffic
sudo ufw default deny incoming
sudo ufw default deny outgoing

#Allow traffic for porst 22, 443, and 80
sudo ufw allow 22       # SSH
sudo ufw allow 80       # HTTP
sudo ufw allow 443      # HTTPS

#Enable ufw to apply the changes
sudo ufw enable

#Check if the settings are applied
sudo ufw status
